default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: khsm

test:
  <<: *default
  database: khsm_test

production:
  <<: *default
  database: khsm_prod
